name = "ContinuationSuite"
uuid = "e82900b0-f859-4727-ae26-3525d706451f"
authors = ["Javier González Monge"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
